spring.application.name=demo
# URL de conexión a tu base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/wsp
# Usuario y contraseña
spring.datasource.username=postgres
spring.datasource.password=root
# (Opcional pero recomendado) El driver
spring.datasource.driver-class-name=org.postgresql.Driver


logging.level.org.springframework.security=DEBUG


# Esta línea le dice a Hibernate que actualice las tablas si tus @Entity cambian
spring.jpa.hibernate.ddl-auto=update

# (Opcional) Esto te muestra el SQL que ejecuta en la consola
spring.jpa.show-sql=true